# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1088/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1088/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cloud/TimeVaryingGraphThreadedNonTimeBoundedRouting

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cloud/TimeVaryingGraphThreadedNonTimeBoundedRouting

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1088/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1088/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cloud/TimeVaryingGraphThreadedNonTimeBoundedRouting/CMakeFiles /home/cloud/TimeVaryingGraphThreadedNonTimeBoundedRouting//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cloud/TimeVaryingGraphThreadedNonTimeBoundedRouting/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/cloud/TimeVaryingGraphThreadedNonTimeBoundedRouting/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TVGGraphCalc

# Build rule for target.
TVGGraphCalc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TVGGraphCalc
.PHONY : TVGGraphCalc

# fast build rule for target.
TVGGraphCalc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/build
.PHONY : TVGGraphCalc/fast

Algo/CalcBestPath.o: Algo/CalcBestPath.cpp.o
.PHONY : Algo/CalcBestPath.o

# target to build an object file
Algo/CalcBestPath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/CalcBestPath.cpp.o
.PHONY : Algo/CalcBestPath.cpp.o

Algo/CalcBestPath.i: Algo/CalcBestPath.cpp.i
.PHONY : Algo/CalcBestPath.i

# target to preprocess a source file
Algo/CalcBestPath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/CalcBestPath.cpp.i
.PHONY : Algo/CalcBestPath.cpp.i

Algo/CalcBestPath.s: Algo/CalcBestPath.cpp.s
.PHONY : Algo/CalcBestPath.s

# target to generate assembly for a file
Algo/CalcBestPath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/CalcBestPath.cpp.s
.PHONY : Algo/CalcBestPath.cpp.s

Algo/DataStruct/DataNode.o: Algo/DataStruct/DataNode.cpp.o
.PHONY : Algo/DataStruct/DataNode.o

# target to build an object file
Algo/DataStruct/DataNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/DataStruct/DataNode.cpp.o
.PHONY : Algo/DataStruct/DataNode.cpp.o

Algo/DataStruct/DataNode.i: Algo/DataStruct/DataNode.cpp.i
.PHONY : Algo/DataStruct/DataNode.i

# target to preprocess a source file
Algo/DataStruct/DataNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/DataStruct/DataNode.cpp.i
.PHONY : Algo/DataStruct/DataNode.cpp.i

Algo/DataStruct/DataNode.s: Algo/DataStruct/DataNode.cpp.s
.PHONY : Algo/DataStruct/DataNode.s

# target to generate assembly for a file
Algo/DataStruct/DataNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/DataStruct/DataNode.cpp.s
.PHONY : Algo/DataStruct/DataNode.cpp.s

Algo/DataStruct/Thread_safe_queue.o: Algo/DataStruct/Thread_safe_queue.cpp.o
.PHONY : Algo/DataStruct/Thread_safe_queue.o

# target to build an object file
Algo/DataStruct/Thread_safe_queue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/DataStruct/Thread_safe_queue.cpp.o
.PHONY : Algo/DataStruct/Thread_safe_queue.cpp.o

Algo/DataStruct/Thread_safe_queue.i: Algo/DataStruct/Thread_safe_queue.cpp.i
.PHONY : Algo/DataStruct/Thread_safe_queue.i

# target to preprocess a source file
Algo/DataStruct/Thread_safe_queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/DataStruct/Thread_safe_queue.cpp.i
.PHONY : Algo/DataStruct/Thread_safe_queue.cpp.i

Algo/DataStruct/Thread_safe_queue.s: Algo/DataStruct/Thread_safe_queue.cpp.s
.PHONY : Algo/DataStruct/Thread_safe_queue.s

# target to generate assembly for a file
Algo/DataStruct/Thread_safe_queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/DataStruct/Thread_safe_queue.cpp.s
.PHONY : Algo/DataStruct/Thread_safe_queue.cpp.s

Algo/DataStruct/bestRouteContainer.o: Algo/DataStruct/bestRouteContainer.cpp.o
.PHONY : Algo/DataStruct/bestRouteContainer.o

# target to build an object file
Algo/DataStruct/bestRouteContainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/DataStruct/bestRouteContainer.cpp.o
.PHONY : Algo/DataStruct/bestRouteContainer.cpp.o

Algo/DataStruct/bestRouteContainer.i: Algo/DataStruct/bestRouteContainer.cpp.i
.PHONY : Algo/DataStruct/bestRouteContainer.i

# target to preprocess a source file
Algo/DataStruct/bestRouteContainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/DataStruct/bestRouteContainer.cpp.i
.PHONY : Algo/DataStruct/bestRouteContainer.cpp.i

Algo/DataStruct/bestRouteContainer.s: Algo/DataStruct/bestRouteContainer.cpp.s
.PHONY : Algo/DataStruct/bestRouteContainer.s

# target to generate assembly for a file
Algo/DataStruct/bestRouteContainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/DataStruct/bestRouteContainer.cpp.s
.PHONY : Algo/DataStruct/bestRouteContainer.cpp.s

Algo/postProcess.o: Algo/postProcess.cpp.o
.PHONY : Algo/postProcess.o

# target to build an object file
Algo/postProcess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/postProcess.cpp.o
.PHONY : Algo/postProcess.cpp.o

Algo/postProcess.i: Algo/postProcess.cpp.i
.PHONY : Algo/postProcess.i

# target to preprocess a source file
Algo/postProcess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/postProcess.cpp.i
.PHONY : Algo/postProcess.cpp.i

Algo/postProcess.s: Algo/postProcess.cpp.s
.PHONY : Algo/postProcess.s

# target to generate assembly for a file
Algo/postProcess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Algo/postProcess.cpp.s
.PHONY : Algo/postProcess.cpp.s

Graph/Edge.o: Graph/Edge.cpp.o
.PHONY : Graph/Edge.o

# target to build an object file
Graph/Edge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/Edge.cpp.o
.PHONY : Graph/Edge.cpp.o

Graph/Edge.i: Graph/Edge.cpp.i
.PHONY : Graph/Edge.i

# target to preprocess a source file
Graph/Edge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/Edge.cpp.i
.PHONY : Graph/Edge.cpp.i

Graph/Edge.s: Graph/Edge.cpp.s
.PHONY : Graph/Edge.s

# target to generate assembly for a file
Graph/Edge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/Edge.cpp.s
.PHONY : Graph/Edge.cpp.s

Graph/IntervalPath.o: Graph/IntervalPath.cpp.o
.PHONY : Graph/IntervalPath.o

# target to build an object file
Graph/IntervalPath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/IntervalPath.cpp.o
.PHONY : Graph/IntervalPath.cpp.o

Graph/IntervalPath.i: Graph/IntervalPath.cpp.i
.PHONY : Graph/IntervalPath.i

# target to preprocess a source file
Graph/IntervalPath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/IntervalPath.cpp.i
.PHONY : Graph/IntervalPath.cpp.i

Graph/IntervalPath.s: Graph/IntervalPath.cpp.s
.PHONY : Graph/IntervalPath.s

# target to generate assembly for a file
Graph/IntervalPath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/IntervalPath.cpp.s
.PHONY : Graph/IntervalPath.cpp.s

Graph/Node.o: Graph/Node.cpp.o
.PHONY : Graph/Node.o

# target to build an object file
Graph/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/Node.cpp.o
.PHONY : Graph/Node.cpp.o

Graph/Node.i: Graph/Node.cpp.i
.PHONY : Graph/Node.i

# target to preprocess a source file
Graph/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/Node.cpp.i
.PHONY : Graph/Node.cpp.i

Graph/Node.s: Graph/Node.cpp.s
.PHONY : Graph/Node.s

# target to generate assembly for a file
Graph/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/Node.cpp.s
.PHONY : Graph/Node.cpp.s

Graph/Path.o: Graph/Path.cpp.o
.PHONY : Graph/Path.o

# target to build an object file
Graph/Path.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/Path.cpp.o
.PHONY : Graph/Path.cpp.o

Graph/Path.i: Graph/Path.cpp.i
.PHONY : Graph/Path.i

# target to preprocess a source file
Graph/Path.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/Path.cpp.i
.PHONY : Graph/Path.cpp.i

Graph/Path.s: Graph/Path.cpp.s
.PHONY : Graph/Path.s

# target to generate assembly for a file
Graph/Path.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/Path.cpp.s
.PHONY : Graph/Path.cpp.s

Graph/TVG.o: Graph/TVG.cpp.o
.PHONY : Graph/TVG.o

# target to build an object file
Graph/TVG.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/TVG.cpp.o
.PHONY : Graph/TVG.cpp.o

Graph/TVG.i: Graph/TVG.cpp.i
.PHONY : Graph/TVG.i

# target to preprocess a source file
Graph/TVG.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/TVG.cpp.i
.PHONY : Graph/TVG.cpp.i

Graph/TVG.s: Graph/TVG.cpp.s
.PHONY : Graph/TVG.s

# target to generate assembly for a file
Graph/TVG.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/TVG.cpp.s
.PHONY : Graph/TVG.cpp.s

Graph/TVG_TIME.o: Graph/TVG_TIME.cpp.o
.PHONY : Graph/TVG_TIME.o

# target to build an object file
Graph/TVG_TIME.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/TVG_TIME.cpp.o
.PHONY : Graph/TVG_TIME.cpp.o

Graph/TVG_TIME.i: Graph/TVG_TIME.cpp.i
.PHONY : Graph/TVG_TIME.i

# target to preprocess a source file
Graph/TVG_TIME.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/TVG_TIME.cpp.i
.PHONY : Graph/TVG_TIME.cpp.i

Graph/TVG_TIME.s: Graph/TVG_TIME.cpp.s
.PHONY : Graph/TVG_TIME.s

# target to generate assembly for a file
Graph/TVG_TIME.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/TVG_TIME.cpp.s
.PHONY : Graph/TVG_TIME.cpp.s

Graph/VisibilityInterval.o: Graph/VisibilityInterval.cpp.o
.PHONY : Graph/VisibilityInterval.o

# target to build an object file
Graph/VisibilityInterval.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/VisibilityInterval.cpp.o
.PHONY : Graph/VisibilityInterval.cpp.o

Graph/VisibilityInterval.i: Graph/VisibilityInterval.cpp.i
.PHONY : Graph/VisibilityInterval.i

# target to preprocess a source file
Graph/VisibilityInterval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/VisibilityInterval.cpp.i
.PHONY : Graph/VisibilityInterval.cpp.i

Graph/VisibilityInterval.s: Graph/VisibilityInterval.cpp.s
.PHONY : Graph/VisibilityInterval.s

# target to generate assembly for a file
Graph/VisibilityInterval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/Graph/VisibilityInterval.cpp.s
.PHONY : Graph/VisibilityInterval.cpp.s

LoadExeption.o: LoadExeption.cpp.o
.PHONY : LoadExeption.o

# target to build an object file
LoadExeption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/LoadExeption.cpp.o
.PHONY : LoadExeption.cpp.o

LoadExeption.i: LoadExeption.cpp.i
.PHONY : LoadExeption.i

# target to preprocess a source file
LoadExeption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/LoadExeption.cpp.i
.PHONY : LoadExeption.cpp.i

LoadExeption.s: LoadExeption.cpp.s
.PHONY : LoadExeption.s

# target to generate assembly for a file
LoadExeption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/LoadExeption.cpp.s
.PHONY : LoadExeption.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TVGGraphCalc.dir/build.make CMakeFiles/TVGGraphCalc.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TVGGraphCalc"
	@echo "... Algo/CalcBestPath.o"
	@echo "... Algo/CalcBestPath.i"
	@echo "... Algo/CalcBestPath.s"
	@echo "... Algo/DataStruct/DataNode.o"
	@echo "... Algo/DataStruct/DataNode.i"
	@echo "... Algo/DataStruct/DataNode.s"
	@echo "... Algo/DataStruct/Thread_safe_queue.o"
	@echo "... Algo/DataStruct/Thread_safe_queue.i"
	@echo "... Algo/DataStruct/Thread_safe_queue.s"
	@echo "... Algo/DataStruct/bestRouteContainer.o"
	@echo "... Algo/DataStruct/bestRouteContainer.i"
	@echo "... Algo/DataStruct/bestRouteContainer.s"
	@echo "... Algo/postProcess.o"
	@echo "... Algo/postProcess.i"
	@echo "... Algo/postProcess.s"
	@echo "... Graph/Edge.o"
	@echo "... Graph/Edge.i"
	@echo "... Graph/Edge.s"
	@echo "... Graph/IntervalPath.o"
	@echo "... Graph/IntervalPath.i"
	@echo "... Graph/IntervalPath.s"
	@echo "... Graph/Node.o"
	@echo "... Graph/Node.i"
	@echo "... Graph/Node.s"
	@echo "... Graph/Path.o"
	@echo "... Graph/Path.i"
	@echo "... Graph/Path.s"
	@echo "... Graph/TVG.o"
	@echo "... Graph/TVG.i"
	@echo "... Graph/TVG.s"
	@echo "... Graph/TVG_TIME.o"
	@echo "... Graph/TVG_TIME.i"
	@echo "... Graph/TVG_TIME.s"
	@echo "... Graph/VisibilityInterval.o"
	@echo "... Graph/VisibilityInterval.i"
	@echo "... Graph/VisibilityInterval.s"
	@echo "... LoadExeption.o"
	@echo "... LoadExeption.i"
	@echo "... LoadExeption.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/cloud/TimeVaryingGraphThreadedNonTimeBoundedRouting/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

